### ISSUE TITLE
Overriding third party components style

### ISSUE THREAD

**Issue by welljs** [gajus/react-css-modules#114]
For example i use `react-bootstrap` button, and want to override padding of `.help-block` to which i have no direct access. 

```javascript
<div className={styles.myDiv}>
	<Input value={this.state.value}/>
</div>
```

With scss everything is simpe:
```scss
.myDiv{
	/*my styles */
	.help-block{ /* <-- this is bootstrap's layout */
		font-size: 1em;
	}
}
```

But how can i do this with `react-css-modules`?
