### ISSUE TITLE
@Keyframes not honoring :global

### ISSUE THREAD

**Issue by chapati23** [gajus/react-css-modules#126]
Global animations seem to be broken.

Input:
```css
:global {
  @keyframes spin {
    0% {
      transform: rotate(0);
    }
    100% {
      transform: rotate(359deg);
    }
  }
}
```

Expected Output:
```css
@keyframes spin {
    0% {
        transform: rotate(0);
    }
    100% {
        transform: rotate(359deg);
    }
}
```

Actual Output:
```css
@keyframes src-___index__spin___uB5Zv {
    0% {
        transform: rotate(0);
    }
    100% {
        transform: rotate(359deg);
    }
}
```
