### ISSUE TITLE
How to use single class which is defined somewhere else.

### ISSUE THREAD

**Issue by nsisodiya** [gajus/react-css-modules#17]
`style.css`:

```css
.font-lg {
    font-size:large;
}
.rfloat {
    float:left;
}
```

I am using `style.css` classes in my `HelloComponent.css`:

```css
.rfloat {
    composes: rfloat from '../../../../css/common/style.css';
}
.font-lg {
    composes: font-lg from '../../../../css/common/style.css';
}
.saveBtn {
    // CSS for save button
}
```

and I am using, `font-lg` class in `HelloComponent.js`:

```js
render () {
    return <span>
        <span styleName='font-lg'><Icon icon='star'/></span>
        <span styleName='rfloat'>Star Component</span>
    </span>
}
```

Every time, I am doing this for using a common class which is defined in common css file. 

Is there a shortcut for this one, so that I would not need to redefine common classes that we need?

Is it possible to do this kind of operations in  `HelloComponent.css`:
 
```css
import rfloat, font-lg from '../../../../css/common/style.css';
.saveBtn {
      // CSS for save button
}
```
