### ISSUE TITLE
other implementation of react-css-module

### ISSUE THREAD

**Issue by craigcosmo** [gajus/react-css-modules#185]
What I see about this is, it replaces the name of CSS class in .jsx and .css or .scss file with a hash string. If it's that's all it does why don't we just do like this.

Our base code before any transpiling is like this

home.scss
```scss
.home {
    width:500px;
}
.box {
   width:200px;
}
```

Home.jsx component

```jsx
render(){
   <div className="home">
       <div className="box"></div>
   <div>
}
```

Now react-css-module will make that become this

home.scss

```scss
.home_1fg8e {
    width:500px;
}
.box_78uuy {
   width:200px;
}
```

```jsx
render(){
   <div className="home_1fg8e">
       <div className="box_78uuy"></div>
   <div>
}
```

Isn't that more natural? Instead of assigning js object as className?

Has my suggestion been thought before but due to drawback it was put off? Or it hasn't been done because of the technical?
