### ISSUE TITLE
Add possibility to append empty class [feature request]

### ISSUE THREAD

**Issue by hinok** [gajus/react-css-modules#201]
Hey,
I would like to have ability to append "empty class" for a parent element because then I can easily override styles for children, especially in conjuction with pseudo classes. Simplified case below:

```scss
.c {
  input { 
    color: red;
  }
  
  // it could be done in other way but that's not the case
  &--sky input {
    color: blue;
  }
  
  // This is exactly what I need, styling based on pseudo
  &--sky input:focus ~ svg path {
    fill: red;
  }
}
```

```jsx
const klass = sky ? 'c--sky' : null;

return (
    <div styleName={cx('c', klass)}>
      <input type="text" placeholder={placeholder} />
      <svg /* paths of svg */ />
    </div>
);
```

At the moment I have to add an insignificant rule to get `c--sky` in my parent element like

```css
.c--sky { z-index: 0; }
```

Many thanks!
