### ISSUE TITLE
Class Composition ? it is equal to the following css ?

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [gajus/react-css-modules#218]
## Class Composition 

```css
.box {
    width: 100px;
    height: 100px;
}
.empty {
    composes: box;
    background: #4CAF50;
}
.full {
    composes: box;
    background: #F44336;
}
``` 
>   it is equal to the following css ?

`===`

```css

.empty {
    width: 100px;
    height: 100px;
    background: #4CAF50;
}
.full {
    width: 100px;
    height: 100px;
    background: #F44336;
}

```

**Comment by xgqfrms-GitHub** [comment]
# OR,  it is equal to the following css ?

`===`

```css
.box-empty {
    width: 100px;
    height: 100px;
    background: #4CAF50;
}
.box-full {
    width: 100px;
    height: 100px;
    background: #F44336;
}

```

**Comment by fuckingdigital** [comment]
Neither nor.
It will end up in
```scss
.box {
    width: 100px;
    height: 100px;
}

.empty {
    background: #4CAF50;
}

.full {
    background: #F44336;
}
```

but it will add two classes like `.box.empty` or `.box.full`
