### ISSUE TITLE
Make it possible to extend child component styles with `styleName` prop

### ISSUE THREAD

**Issue by publicJorn** [gajus/react-css-modules#220]
I might have misunderstood the [several](https://github.com/gajus/react-css-modules/issues/119#issuecomment-219322811) [issues](https://github.com/css-modules/css-modules/issues/139) and the [docs](https://github.com/gajus/react-css-modules#loops-and-child-components), but as far as I can tell, this following is not possible..

..and it would be awesome if it could be done :)

I have the following situation:

```
app/
app/Start/index.css
app/Start/index.js
app/H1/index.css
app/H1/index.js
```

```css
/* Start/index.css */

.title {
  composes: h1 from 'h1.css';
  text-align: center; /* this is not applied */
}
```

```javascript
// Start/index.js

import React from 'react'
import CSSModules from 'react-css-modules'
import H1 from '../H1'
import styles from './index.css'

class Start extends React.Component {
  render() {
    console.log('Start', styles)

    return (
      <div>
        <H1 styleName='title'>The title</H1> // class name not applied
      </div>
    )
  }
}

export default CSSModules(Start, styles)
```

```css
/* H1/index.css */

.h1 {
  color: red; /* this IS applied */
}
```

```javascript
// H1/h1.js

import React from 'react'
import CSSModules from 'react-css-modules'
import styles from './index.css'

class H1 extends React.Component {
  render () {
    console.log('H1', styles)
    return (<h1 styleName='h1'>{this.props.children}</h1>) // this IS applied
  }
}

export default CSSModules(H1, styles)
```

With my CSS Modules setup, the expected result is:

```html
<div>
  <h1 class="Start__title H1__h1">The title</h1>
</div>
```

Actual result is:

```html
<div>
  <h1 class="H1__h1">The title</h1>
</div>
```

Interestingly, the console reveals that the `Start` styles object does compose as expected:

```
-- First log:
'Start'
Object { title: 'Start__title H1__h1' }

-- Second log:
'H1'
Object { title: 'H1__h1' }
```

Also see: [http://stackoverflow.com/questions/38869244/add-stylename-property-on-react-component-when-using-react-css-modules](http://stackoverflow.com/questions/38869244/add-stylename-property-on-react-component-when-using-react-css-modules)

**Comment by publicJorn** [comment]
Btw: I noticed that, in the above construction, the `H1` component does get a `className` property with `'Start__title H1__h1'`.

So something like the following is possible:

```javascript
// H1/h1.js **modified

import React from 'react'
import CSSModules from 'react-css-modules'
import styles from './index.css'

class H1 extends React.Component {
  render () {
    const props = { styleName='h1' }
    if (this.props.className) {
      props.className = this.props.className
    }

    return <h1 {...props}>{this.props.children}</h1>
  }
}

export default CSSModules(H1, styles)
```

2 Remarks:
- We need to pass BOTH className and styleName, because `this.props.className` doesn't go deeper then one `composes` statement. ***A**
- However, passing both means we get the styleName twice ***B**

***A:**

```css
/* H1/index.css */
.headings {
  font-size: 5rem;
}

.h1 {
  composes: headings;
  color: red; /* this IS applied */
}
```

```css
/* Start/index.css */

.title {
  composes: h1 from 'h1.css';
  text-align: center; /* this is not applied */
}
```

Using just `<h1 className={this.props.className}>{this.props.children}</h1>` in `H1/index.js` will result in:

```html
<div>
  <h1 class="Start__title H1__h1">The title</h1>
</div>
```

instead of:

```html
<div>
  <h1 class="Start__title H1__h1 H1__headings">The title</h1>
</div>
```

***B:**

Passing both results in this:

```html
<div>
  <h1 class="Start__title H1__h1 H1__h1 H1__headings">The title</h1>
</div>
```

**Comment by publicJorn** [comment]
Ok I must have been sleeping.. I now understand that what I want to do is accomplished by setting the `styles` prop on `H1` like so:

```css
/* Start/index.css */

.h1 { /* needs to be the same selector as in original css file, that we compose from */
  composes: h1 from '../H1/index.css';
  text-align: center;
}
```

```javascript
// ...
import styles from './index.css'

class Start extends React.Component {
  render() {
    return (
      <div>
        <H1 styles={styles}>The title</H1>
      </div>
    )
  }
}
```

> It might be better to make a separate css file `Start/h1.css` so it's more clear what we overwrite.

Thoughts:

- This is actually in the docs, but it doesn't feel intuitive to me. It would be far more natural if we could just always use the proposed method (only `styleName="<whatever>"`). _So this request still stands_
- Similarly it feels a bit restrictive that you have to use the same selector. But there might be a technical limitation to this (same key)
- I found that you do have to pass along a whole css file, this does not work: `<H1 styles={styles.h1}>The title</H1>`

So @gajus, if the initial request (see title) would still be possible, I'd like to keep this issue open. 
Otherwise, feel free to close it

**Comment by fuckingdigital** [comment]
I had the very same issue.
It took me a while to understand, that react-css-modules is not meant to work like that. It has a strict approach, which is good.
For this problem I mixed react-css-modules with _normal_ CSS Modules.
I striped out a lot of stuff to make this less complicated.

Hope this maybe be kind of a solution:

User Stories:
- I want to have a framework-like column component.
- I want to add custom styles (means different grid behaviors like “.lg-2-3 .xl-1-3” for example)
- I want to add variations which the framework component will not know about (like ".red-col" or “.col-with-underline”).

Problems:
- I need two keys, one for the real grid variants, one for additional styles which are not bound to the original framework component.

The Example:

The framework in a node package (which I will use in a lot of projects):
```
framework/Grid/Col.js
framework/Grid/styles.scss
```

My example project:
```
components/Grid/Col.js
components/Grid/styles.scss
components/ExampleComponentWithColUse/ExampleComponentWithColUse.js
components/ExampleComponentWithColUse/styles.scss
```

The Framework:

```javascript
// Grid/Col.js

import React from 'react';
import CSSModules from 'react-css-modules';
import styles from './styles.scss';

function Col(props) {
    // sizes will be a string with styleNames that overwrite this components styles
    // styleVariants will be a string with classes or one class that this component does not have to know anything about
    const { sizes, styleVariants } = props;
    // this will provide the fallback class 'col'
    const styleNames = sizes || 'col';
    return (
        <div className={styleVariants} styleName={styleNames}>
            {props.children}
        </div>
    );
}

export default CSSModules(Col, styles, { allowMultiple: true });

```

```scss
// Grid/styles.scss

.col {
    box-sizing: border-box;
    padding-left: 20px;
    padding-right: 20px;
}

```

Example project files:

```javascript
// components/Grid/Col.js

import React from 'react';
import FrameworkCol from 'framework/Grid/Col';
import styles from './styles.scss';

function Col(props) {

    return <FrameworkCol styles={styles} sizes={props.sizes} styleVariant={props.styleVariant}>{props.children}</FrameworkCol>;
}

export default Col;
```

```scss
//components/Grid/styles.scss

.col {
    box-sizing: border-box;
    padding-left: 30px;
    padding-right: 30px;
    width: 100%;
}

.sm-1-2 {
    composes: col;
    width: 50%;
}

.lg-1-3 {
    composes: col;
    @include mediaquery('lg') {
        width: 33.333%;
    }
}
```

```javascript
// components/MyExampleComponent/MyExampleComponent.js
// now the Col component will be used

import React from 'react';
import Col from '../Grid/Col';
import styles from './styles.scss';

function MyExampleComponent(props) {
    // see the styleVariant — it uses CSS Modules, not (!!!) react-css-modules (i think this a good way to add additional classes or a new scope, key or however you like to call it)
    return <Col sizes="sm-1-2 lg-1-3" styleVariant={styles.specialColColor}>{props.children}</Col>;
}

export default MyExampleComponent;
```

```scss
//components/MyExampleComponent/styles.scss

.specialColColor {
    background-color: red;
}
```

Let me know your thoughts.
