### ISSUE TITLE
How to override styles from another css file

### ISSUE THREAD

**Issue by sky93** [gajus/react-css-modules#282]
I have a css file (`main.css`) and I'd like to override it using another css file (`overrides.css`). But I have problem doing it as they are in different files and they get different hashes.

This is my css:
```css
/* main.css */
.mainContainer {
    padding: 16px;
    margin: 16px;
    background-color: palevioletred;
    border-radius: 5px;
}

.mainContainer h1{
    color: white;
}
```

```CSS
/* overrides.css */
.mainContainer h1{
    color: blue;
}
```

According to @sohkai suggestion in [here](https://github.com/gajus/react-css-modules/issues/94#issuecomment-185494090) I used `Object.assign()` to combine css files but it didn't help.  This is my component:

```ES6
import React from 'react';
import Main from './main.css';
import Overrides from './overrides.css';
const Style = Object.assign({}, Overrides, Main);

class Sample extends React.Component{
  render(){
    return (
      <div className={Style.mainContainer}>
        <h1>Hello</h1>
        <p>Hello CSS modules!</p>
      </div>
    );
  }
}

export default Sample;
```

I expect my `h1` to become blue but it won't. This is my compiled css:
```CSS
/* main.css */
._1pXpG {
    padding: 16px;
    margin: 16px;
    background-color: palevioletred;
    border-radius: 5px;
}

._1pXpG h1{
    color: white;
}
```

```CSS
/* overrides.css */
.Wmy0p h1{
  color: blue;
}
```

I expect `.Wmy0p h1` to be `._1pXpG h1` so it can override. But it won't. Note that if you just paste the content of `overrides.css` at the bottom of the main css it will work but I need my override css file to be in a separate file. 

Thanks in advance,
