### ISSUE TITLE
css module is undefined in async chunks when not specify `{allChunks:true}` of `extract-text-webpack-plugin`

### ISSUE THREAD

**Issue by Duan112358** [gajus/react-css-modules#55]
I don't want extract all css into one css, for I use async route .
[bundle-loader](https://github.com/webpack/bundle-loader) enables me to define async routes ,combined with [react-router-component](https://github.com/STRML/react-router-component)
```jsx
import React from 'react'
import ReactDom from 'react-dom'

import {  NotFound, Locations, Location } from 'react-router-component'
import NProgress from 'nprogress'
import AsyncLoader from './async-loader'

// bundle-loader, use require.ensure([], (require) -> {
//      require('some module you want to load async');
// })
import Home from 'bundle?lazy!./home'
import About from 'bundle?lazy!./about'
import Messages from 'bundle?lazy!./messages'
import Test from 'bundle?lazy!./test'
import NotFoundPage from 'bundle?lazy!./notfound'

require('../scss/reset.scss')

class App extends React.Component {
    render() {
        return (
            <Locations hash>
                <Location path="/" handler={AsyncLoader(Home)}/>
                <Location path="/about" handler={AsyncLoader(About)}/>
                <Location path="/messages/:id" handler={AsyncLoader(Messages)}/>
                <Location path="/test" handler={AsyncLoader(Test)}/>
                <NotFound handler={AsyncLoader(NotFoundPage)}/>
            </Locations>
        )
    }
}

ReactDom.render(<App/>, document.getElementById('app'))

```

the AsyncLoad definition:
``` jsx
import React, {Component} from 'react';

class AsyncLoader extends Component {
    constructor(){
        super();
        this.state = {

        }
    }

    componentDidMount() {
      this.props.component((Component) => {
        this.setState({
          Component: Component
        });
      });
    }

    render() {
      var Component = this.state.Component;
      if (Component) {
        return <Component {... this.props}/>
      } else {
        return <div>Loading...</div>;
      }
    }
}

module.exports = function asyncLoader(component) {
    return <AsyncLoader component={component}/>
}

```
I define a Hello component
``` jsx
import React, { Component } from 'react'

import CSSModules from 'react-css-modules'
import styles from './index.scss'

@CSSModules(styles)
class Hello extends Component {
    constructor(){
        super();

        this.state = {
            message: 'hello world'
        }
    }

    sayHello(e){
        this.setState({
            message: 'Hey, life is a struggle.'
        });
    }

    render(){
        return <div styleName='container'>
            <div styleName='message'>
                { this.state.message }
            </div>
            <button styleName='btn' onClick={this.sayHello.bind(this)}>Say Hello</button>
        </div>
    }
}

export default Hello
``` 
and the `index.scss`

```scss
$color-primary: #63c7d3;
$color-bg: #efefef;

.container {
    margin: 10px;
    padding: 10px;
    background-color: $color-bg;
}

%text-center {
    text-align: center;
}

.btn {
    border-radius: 2px;
    border: none;
    box-shadow: none;
    text-align: center;
    padding: 5px 10px;
    line-height: 1em;
}

%btn-primary{
    @extend %btn;
    background-color: $color-primary;
    color: white;
}

.message {
    @extend %text-center;
}
```
the home page is following
``` jsx
import React from 'react'
import { Link } from 'react-router-component'
import { Hello } from 'wepiao'

class Home extends React.Component {

  render() {

    return (
      <div>
        <Hello />
        <ul>
            <li>
                <Link href="/about">About</Link>
            </li>
            <li>
                <Link href="/messages/1">Messages</Link>
            </li>
        </ul>
      </div>
    )
  }
}

export default Home

```

when i navigate to route home,
![image](https://cloud.githubusercontent.com/assets/1957818/10932520/70441f7e-830c-11e5-9a9a-066ddcc9c0b5.png)

when specify `allChunks: true` in [extract-text-webpack-plugin](https://github.com/webpack/extract-text-webpack-plugin), it works.

so, how to fixed the issues in async chunks, thks
