### ISSUE TITLE
Overriding styles

### ISSUE THREAD

**Issue by sarink** [gajus/react-css-modules#94]
(I have already read https://github.com/gajus/react-css-modules#extending-component-styles)

Let's say I have a basic component.... 

```js
class MyComponent extends Component {
  render() {
    return (
      <div styleName="container">
        <div styleName="inner-1">inner-1</div>
        <div styleName="inner-2">inner-2</div>
        <div styleName="inner-3">inner-3</div>
        <div styleName="inner-4">inner-4</div>
      </div>
    );
  }
}
```

Now, I want to use it in some other component. This other component needs to ever-so-slightly modify `MyComponent`s styles (let's say... modify the background-color, but leave everything else the same)

```js
class MyWrapper extends Component {
  render() {
    return <MyComponent styles={this.props.styles} />;
  }
}
```

Does this mean that `.my-wrapper.scss` needs to define every single class that `MyComponent` has?

```js
/* my-wrapper.scss */
.container {
  composes: container from './my-component.scss';
  background-color: red; /* our one override */
}
.inner-1 {
  composes: inner-1 from './my-component.scss';
}
.inner-2 {
  composes: inner-2 from './my-component.scss';
}
.inner-3 {
  composes: inner-3 from './my-component.scss';
}
.inner-4 {
  composes: inner-4 from './my-component.scss';
}
```

... Is this the only way to achieve this? Is there some other manner of inheriting or extending styles that I'm unaware of? Because I find this architecture very difficult to manage.

**Comment by SohKai** [comment]
If you know the component that `MyWrapper` will wrap, you can use `Object.assign()` (or similar) to import from multiple modules to avoid redefining the other styles:

```css
/* my-wrapper.scss */
.container {
  composes: container from './my-component.scss';
  background-color: red; /* our one override */
}
```

```js
/* my_wrapper.js */
import myContainerStyles from 'my-container.scss';
import myWrapperStyles from 'my-wrapper.scss';
const style = Object.assign({}, myContainerStyles, myWrapperStyles);

class MyWrapper extends Component {
  render() {
    return <MyComponent styles={this.props.styles} />;
  }
}
```

**Comment by sarink** [comment]
@SohKai That's great, unless you have a multiple nested components. Consider something as simple as.....

Button > CircleButton > CircelEditButton > DarkCircleEditButton ..... React itself is built around the idea of composing and re-using modules in this fashion.

Now, let's say I had a component that wanted to use DarkCircleEditButton, and maybe float it right, or something (obviously this example is contrived because you could put a container around it, but that's not really the point)

Are you supposed to

```
const style = Object.assign({}, buttonStyles, circleButtonStyles, circleEditButtonStyles, darkCircleEditButtonStyles, myComponentStyles);
```

... how is this problem not affecting more people? I struggle with this daily and I just have to wonder, am I using this library wrong? Or was this a giant oversight by the authors? I'm incredibly lost.

**Comment by gajus** [comment]
> Equally ridiculous is the idea that MyComponent should have to re-define every single class name being utilized by all these components just so that it can override one property.

What alternative do you propose?

This approach gives the most flexibility at a cost of requiring to simply use `Object.assign` (as mentioned by @SohKai) when wanting to combine multiple styles.

> Button > CircleButton > CircelEditButton > DarkCircleEditButton ..... React itself is built around the idea of composing and re-using components in exactly this fashion.
> Now, let's say I had a component that wanted to use DarkCircleEditButton, and maybe float it right, or something (obviously this example is contrived because you could put a container around it, but that's not really the point)

By the sound of it, you are trying to solve a problem at a different level. You are not supposed to extend styles using `react-css-modules` API. You are supposed to do it within the CSS module itself.

See https://github.com/css-modules/css-modules#dependencies

**Comment by gajus** [comment]
> We compose complex components and override one prop in both React and CSS ALL the time. I'm not sure why what seems like such a common use case is so difficult.

Are you going to propose an alternative API/ implementation or a utility function?

**Comment by SohKai** [comment]
@sarink Ah, OK, I think I get where you're going with this. I didn't realize you meant using something like your original base component when you started nesting the buttons.

This is somewhat of a limitation with CSS Modules and how it works. Depending on how strict / pure you interpret the philosophy behind CSS Modules, this is a use case that's not entirely supported–especially when you factor in that CSS Modules was not designed completely in the same philosophy of React; generally, having parent components that directly modify the styling of child components goes against the philosophy of CSS Modules. For effects outside of the component (ie. positioning and margins and etc), I think adding a container element rather than trying to do it in the component is the right choice in most cases.

But for modifying internal structure, let's stay with your button components to stay consistent, here's two options:
* You could use a mixin to fill out all of the classes to be composed and then add their style overrides afterwards.
```css
/* my-wrapper.scss */
@mixin my-component-classes() {
    .container {
        composes: container from './my-component.scss';
    }

    .inner-1 {
        composes: inner-1 from './my-component.scss';
    }
    ... /* all the other inner classes */ 
} 

@include my-component-classes();
.container {
    background-color: red; /* our one override */
}

.inner-1 {
    /* more overrides */
}
```
* You could use globals for the nested classes and then rely on child selectors to make sure they keep their local scope
```css
/* my-component.scss */
.container {
    ...

    > :global {
        .inner-1 { ... }
        ... /* all the other inner classes */
    }
}

/* my-wrapper.scss */
.container {
    composes: container from './my-component.scss';

    > :global {
        .inner-1 { /* more overrides */ }
    }
}
```

In general though, if you find yourself having to modify styles in a child component, it's likely you've misdesigned some part and could benefit from taking a step back and rethinking it through.

**Comment by elado** [comment]
@gajus as an API suggestion, how about something like:

```scss
// MyComponent.scss
.component {
  background-color: yellow;
  font-weight: bold;
}

// MyList.scss
.list {
  // ...
}

.listItem {
  border: 1px solid red;
}

.listItem {
  // ▼ this will generate ".listItem_[hash] .component_[hash] {}" rule instead of just .listItem_[hash]
  override-child: component from './MyComponent.scss';
  background-color: red;
}
```

```jsx
// MyComponent.jsx
import styles from './MyComponent.scss'
export default ({ title }) => <div className={styles.component}>{title}</div>

// MyList.jsx
import styles from './MyList.scss'
export default ({ titles }) => (
  <div className={styles.list}>
    {titles.map(title => <div key={title} className={styles.listItem}><MyComponent title={title} /></div>)}
  </div>
)
```

**Comment by liady** [comment]
@elado +1 that's a very good idea. The reference can even be in the selector level:

```
// MyList.scss
.listItem :external(.button from './MyButton.scss') {
  font-size: 17px;
}
```
And that way even the child element can have a specific rule for when it is inside a container:
```
// MyButton.scss
:external(.listItem from './List.scss') .button {
  font-size: 17px;
}
```

**Comment by gajus** [comment]
@elado You are proposing CSS modules implementation changes. As such, these suggestions belong to https://github.com/css-modules/css-modules.

**Comment by elado** [comment]
@gajus yeah, realized that and posted here https://github.com/css-modules/css-modules/issues/139

**Comment by xenongattz** [comment]
I have problem when importing multiple styles:
"Cannot use anonymous style name with more than one stylesheet import."

Code for import is:
`
import pageStyles from './signUp.css'
import calendarStyles from 'rc-calendar/assets/index.css'
let styles = Object.assign({}, pageStyles, calendarStyles)
`

Trying to combine styles but compile fails.

**Comment by gajus** [comment]
@xenongattz Wrong repository.

> Cannot use anonymous style name with more than one stylesheet import.

comes from:

https://github.com/gajus/babel-plugin-react-css-modules

**Comment by puopg** [comment]
I just wanted to add my experience here since it might help. So I had the same issue as the OP, where I created a generic component but I needed to adjust a few things about how it rendered. (Things like, I want the text here to be bold, or hover color, etc).

Last thing I wanted to do is have a configuration based approach to give override styles to the component since, well, I think thats lame. I also didn't desire to wrap the component and extend the styles object or mess with imports for something so simple. So what I did?

```javascript
// ParentComponent.tsx
render() {
   return(
      <div className={styles.parentContainer}>
         <MyComponent/>
      </div>
   );
}

// MyComponent.tsx
render() {
   return(
      <div className={`my-component ${styles.myComponent}`}>
         <span className={`change-me ${styles.changeMe}`}>CHANGE MY COLOR</span>
      </div>
   );
}
```

```css
// ParentComponent.scss
.parent-container {
   :global(.my-component > .change-me) {
      color: blue;
   } 
}

// MyComponent.scss
.change-me {
   color: red;
}
```

You don't even need the my-component className but as the example i just am leaving it there. Since the rule is namespaced by the parent container as well, it won't collide and creates a more specific selector which will win over the base modularized 'change-me' class name.
